version: '2.1'

services:
  express:
    container_name: "ttt-express"
    build:
      context: ${PWD-.}
    volumes:
      - ${PWD-.}:/app
      - /app/node_modules/
    ports:
      - "8090:8090"
    links:
      - mongo
  mongo:
    container_name: "ttt-mongo"
    image: "mongo:3.4.3"
    ports:
      - "27017:27017"
  redis:
    container_name: "ttt-redis"
    image: "redis:3.0"
    ports:
      - "6379:6379"
